name: 'simple_http_gen'
description: A Simple Http Code Generator.
homepage: https://github.com/tjdwns5063/simple_http_gen
version: 0.0.4

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  source_gen: ^1.4.0
  analyzer: ^6.2.0
  code_builder: ^4.7.0
  build: ^2.4.1
  dart_style: ^2.3.3
  simple_http_annotation: ^0.0.1

dev_dependencies:
  build_runner: ^2.4.6
  http: ^1.1.0
  build_test: ^2.2.0
  test: ^1.24.6

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

topics:
- network
- http
- generator

